spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/starter
    username: starter
    password: starter
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
  h2:
    console:
      enabled: false
