version: '2'
services:
  starter-postgresql:
    image: postgres:10.4
    volumes:
    - ./data/starter/postgresql/:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=starter
    - POSTGRES_PASSWORD=starter
    ports:
    - 5432:5432
